<div id="loading"></div>

<div id="error" class="rel"></div>

<div id="reportbug" class="rel">
    <div class="close abs"></div>
    <div>
        Please describe the bug with as much detail as possible. If you are presently playing a game, the game details will be automatically included.
    </div>
    <textarea></textarea>
    <div class="send">SEND</div>
</div>

<div id="feedback" class="rel">
    <div class="close abs"></div>
    <div>
        All suggestions, questions, and general feedback welcome!
    </div>
    <textarea></textarea>
    <div class="send">SEND</div>
</div>

<div id="changecolor" class="rel">
    <div class="close abs"></div>
    <div>
        Please select the deck color you would like to use:
    </div>
    <div class="colorselect">
    </div>
    <div>
        Purchase more deck colors from the shop!
    </div>
</div>

<div id="contextmenu" class="rel">
    <div class="close abs"></div>
    <ul class="menu">
        <li class="main">Main Menu</li>
        <li class="review">Review Game</li>
        <li class="changecolor enabled" rel="#changecolor">Deck Color</li>
        <li class="enabled feedback" rel="#feedback">Feedback</li>
        <li class="enabled reportbug" rel="#reportbug">Report a Bug</li>
        <li class="enabled account"><a href="/account">Account Settings</a></li>
        <li class="enabled logout">Log Out</li>
    </ul>
</div>
