<div id="content-scale-stage">
    <div id="content-wrapper" class="hide">
        <div id="title-wrapper" class="rel">

            <div id="title-icon" rel="#contextmenu"></div>
            <div id="title">PURE TRIPLE TRIAD</div>

            <div id="status-wrapper">
                <div id="mute-icon"></div>
                <div id="coins">COINS: <span class="coin-balance"></span></div>
            </div>
        </div>
        
        <div id="content" class="rel clear">
            <?php echo $this->partial('overlays.phtml', array()) ?>
        </div>
        
        <div id="footer-wrapper">
            <div id="rules" class="fl hide"></div>
            <div class="fr"><img src="/images/html5logo20.png" /></div>
            <div id="footer-brand" class="fr">Standalone archival edition</div>
        </div>
    </div>
</div>

<div id="browsers-wrapper" class="hide">
    <div id="browsers">
        <div class="title">UPGRADE YOUR BROWSER TO PLAY:</div>
        <div class="products">
            <ul>
                <li><img src="/images/browsers/64-chrome.png" alt="Chrome"> 8+ </li>
                <li><img src="/images/browsers/64-firefox.png" alt="Firefox"> 4+ </li>
                <li><img src="/images/browsers/64-ie.png" alt="Internet Explorer"> 9+ </li>
                <li><img src="/images/browsers/64-opera.png" alt="Opera"> 11+ </li>
                <li><img src="/images/browsers/64-safari.png" alt="Safari"> 5+ </li>
            </ul>
            <div class="clear"></div>
        </div>
        <div class="desc">PURE TRIPLE TRIAD REQUIRES AN HTML 5 COMPLIANT BROWSER</div>
    </div>
</div>
