date.timezone = UTC
display_errors = Off
display_startup_errors = Off
expose_php = Off
log_errors = On
error_log = /var/www/app/var/log/php-error.log
session.save_path = /var/www/app/var/sessions
session.use_strict_mode = 1
session.use_only_cookies = 1
session.cookie_httponly = 1
session.cookie_samesite = Lax
session.gc_maxlifetime = 86400
upload_max_filesize = 2M
post_max_size = 2M
max_execution_time = 30
allow_url_fopen = Off
