<div id="board">
    <div id="svgBoard"></div>
    <div class="overlay"></div>
</div>
<div id="seed" class="hide"><?php echo $this->clientdata ?></div>
<!--
<div id="footer">
    
    <div class="fl player-details player-one">
        <div class="picture">
            <img src="https://graph.facebook.com/<?php echo $this->p1['id']; ?>/picture?type=small" />
        </div>
        <div class="name">
            <?php echo $this->p1['name']; ?>
        </div>
    </div>
    
    <div class="fl game-details">
        <a class="review-game" href="javascript:">Review Game</a>
        <a class="spawn" href="javascript:">Spawn</a>
    </div>
    
    <div class="fl player-details player-two">
        <div class="picture">
            <img src="https://graph.facebook.com/<?php echo $this->p1['id']; ?>/picture?type=small" />
        </div>
        <div class="name">
            <?php echo $this->p1['name']; ?>
        </div>
    </div>
    
    <div class="clear"></div>
</div>
-->