<div id="header" class="full-width">
    <span class="title cufon invisible boister">PureTripleTriad</span>
    
    <ul id="topmenu" class="dropdown">
        <li><a class="play cufon invisible boister play" href="/game">Play</a></li>
        <li><a class="play cufon invisible boister invite" href="javascript:">Invite</a></li>
        <li><a class="play cufon invisible boister howto" href="javascript:">How to</a>
            <ul>
                <li><a class="play cufon invisible boister" href="/replay?gameid=1">Basics</a></li>
            </ul>
        </li>
        <li><a class="play cufon invisible boister news" href="">News</a></li>
    </ul>
</div>