<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <script type="text/javascript" language="javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script type="text/javascript" language="javascript" src="/js/jquery-ui-1.8.9.custom.min.js"></script>
    <script type="text/javascript" language="javascript" src="/js/gh.min.js"></script>
    <script type="text/javascript" language="javascript" src="http://cdn.jquerytools.org/1.2.6/tiny/jquery.tools.min.js"></script>
    <?php echo $this->headScript() ?>
    
    <link rel="stylesheet" href="/css/common.css" type="text/css" media="all" />
    <?php echo $this->headLink() ?>
</head>
<body>
    <?php echo $this->layout()->content ?>
</body>
</html>